### PR TITLE
added CLI arg and ini file parsing and example ini file

### PR DESCRIPTION
**Pull request by gogurtenjoyer**
example CLI usage:
`python mps_diffusers.py --profile less-steps -p "a gleaming golden dragon statue" -n "night, indoors, mall"`
can use the `-h` flag to view the args - may want to update profiles.ini (I made this before I saw the new samplers added). Profile and negative prompt are optional, but positive prompt is required.

Also: currently it keeps the `while True` looping, but I could add a 'number of generations' flag to the args if needed. Also will add more args to override the .ini settings if present in the future.

### CODE REVIEW

**Comment by whosawhatsis** [comment]
Looks great!

**Comment by whosawhatsis** [comment]
hmm, actually, something's not working. I'm getting this:

```
Traceback (most recent call last):
  File "/Users/who/code/mps_diffusers/mps_diffusers.py", line 68, in <module>
    st['fp16'] = json.loads(st['fp16'].lower())
KeyError: 'fp16'
```

**Comment by whosawhatsis** [comment]
Ah, you need to be in the folder for it to pick up the init file.

**Comment by gogurtenjoyer** [comment]
Ah, I'll add something to fix that in my next PR - sorry about that!

**Pull request merged**
